title: Kalyani Kavathekar
logo: /assets/img/logo.jpg
description: Agile Certified Practitioner (PMI-ACP) with over 16 years of experience  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
